# Fly.io configuration for SecCheck Security Scanner Worker

app = "sec-check-worker"
primary_region = "fra" # Frankfurt - close to Supabase and Upstash

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  WORKER_CONCURRENCY = "2"

# Background worker process - no HTTP service needed
[processes]
  worker = "node dist/index.js"

[machine]
  # VM resources
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

  # Keep background worker running (no auto-stop for workers)
  auto_stop_machines = false
  min_machines_running = 1
  max_machines_running = 2

  # Machine lifecycle settings
  kill_signal = "SIGTERM"
  kill_timeout = "30s"

# No [http_service] or [[services]] section for background workers

# Environment variable placeholders (set these with flyctl secrets)
# DATABASE_URL - PostgreSQL connection string
# REDIS_URL - Redis connection string for BullMQ